dist: trusty
sudo: require
compiler: gcc
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - cmake
      
script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    - gcc -v && g++ -v && cmake --version
